function P = vrs_params()
%VRS_PARAMS Johnson VRS 第一版演示参数。
% 参数来源：NASA/TP-2005-213477 中的 D6075 算例和表 4 标称边界。
% 这些参数只用于跑通结构，不代表本课题最终目标机参数。

P.source = "NASA/TP-2005-213477 D6075 demonstration";

P.environment.rho = 1.225;              % kg/m^3
P.rotor.R = 5.97;                       % m
P.rotor.Omega = 360 * 2*pi / 60;       % rad/s
P.rotor.mass_demo = 3500;               % kg
P.rotor.g = 9.80665;                    % m/s^2

P.model.kappa = 1.10;                   % non-ideal induced-loss factor
P.model.f_vrs = 1.00;                   % VRS increment strength
P.model.tau_rev = 14;                   % rotor revolutions

P.boundary.VzA = -1.50;                 % baseline join A
P.boundary.VzB = -2.10;                 % baseline join B
P.boundary.VzD = -0.20;                 % VRS increment start
P.boundary.VzN = -0.45;                 % upper neutral boundary
P.boundary.qN = 0.85;                   % total inflow at N
P.boundary.VzX = -1.50;                 % lower neutral boundary
P.boundary.qX = 1.25;                   % total inflow at X
P.boundary.VzE = -2.00;                 % VRS increment end
P.boundary.muC = 0.75;                  % baseline returns to momentum theory
P.boundary.muM = 0.95;                  % VRS increment fully disabled

P.numeric.T_min = 1.0;                  % N, numerical protection only
P.numeric.tol = 1e-10;

P.demo.T_ref = P.rotor.mass_demo * P.rotor.g;

% Numeric vector passed into the MATLAB Function block.
P.vector = [ ...
    P.environment.rho; ...
    P.rotor.R; ...
    P.rotor.Omega; ...
    P.model.kappa; ...
    P.model.f_vrs; ...
    P.model.tau_rev; ...
    P.boundary.VzA; ...
    P.boundary.VzB; ...
    P.boundary.VzD; ...
    P.boundary.VzN; ...
    P.boundary.qN; ...
    P.boundary.VzX; ...
    P.boundary.qX; ...
    P.boundary.VzE; ...
    P.boundary.muC; ...
    P.boundary.muM; ...
    P.numeric.T_min; ...
    P.numeric.tol];
end
